version: '3'
services:
  webui:
    container_name: lamacpp-back
    build:
      context: Back/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Back/models:/app/models/
    ports:
      - 8000:8000
  front:
    container_name: lamacpp-front
    build:
      context: Front/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:5173
    env_file:
      - .env